steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://gcb-examples/.netrc.enc', '.']
  dir: 'go-dep-private-builder'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - kms
    - decrypt
    - --ciphertext-file=./.netrc.enc
    - --plaintext-file=./.netrc
    - --location=global
    - --keyring=gcb-keyring
    - --key=github-key
  dir: 'go-dep-private-builder'
- name: 'gcr.io/cloud-builders/go:alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      echo === CREATE GOPATH ===
      . /builder/prepare_workspace.inc
      prepare_workspace
      echo === DEP ===
      cp .netrc ~/.netrc
      go get github.com/golang/dep/cmd/dep
      ./gopath/bin/dep ensure
      echo === INSTALL ===
      go install .
  env: ['PROJECT_ROOT=go-dep-private-builder']
  dir: 'go-dep-private-builder'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-dep-private-builder', '.']
  dir: 'go-dep-private-builder'
images: ['gcr.io/$PROJECT_ID/go-dep-private-builder']
