steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      echo === CREATE GOPATH ===
      . /builder/prepare_workspace.inc
      prepare_workspace
      echo === DEP ===
      cat <<EOF >~/.netrc
      machine github.com
          login nirasan
          password $_GITHUB_ACCESS_TOKEN
      EOF
      go get github.com/golang/dep/cmd/dep
      ./gopath/bin/dep ensure
      echo === INSTALL ===
      go install .
  env: ['PROJECT_ROOT=go-dep-private-builder2']
  dir: 'go-dep-private-builder2'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-dep-private-builder2', '.']
  dir: 'go-dep-private-builder2'
images: ['gcr.io/$PROJECT_ID/go-dep-private-builder2']
