steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
  env: ['PROJECT_ROOT=github.com/nirasan/gcb-examples/go-k8s']
  dir: 'go-k8s'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-k8s:$REVISION_ID', '.']
  dir: 'go-k8s'
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/go-k8s:$REVISION_ID']
  dir: 'go-k8s'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/gcb-deployment'
  - 'gcb=gcr.io/$PROJECT_ID/go-k8s:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcb-cluster-1'