steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
  env: ['PROJECT_ROOT=go-builder']
  dir: 'go-builder'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-builder', '.']
  dir: 'go-builder'
images: ['gcr.io/$PROJECT_ID/go-builder']


