steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      echo === CREATE GOPATH ===
      . /builder/prepare_workspace.inc
      prepare_workspace
      echo === DEP ===
      go get github.com/golang/dep/cmd/dep
      ./gopath/bin/dep ensure
      echo === INSTALL ===
      go install .
  env: ['PROJECT_ROOT=go-dep-builder']
  dir: 'go-dep-builder'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-dep-builder', '.']
  dir: 'go-dep-builder'
images: ['gcr.io/$PROJECT_ID/go-dep-builder']
